UPDATE: Hacemos un output para ver que funcione el endpoint correctamente y que sea satisfactoria la prueba e2e

diff --git a/devops/Jenkinsfile b/devops/Jenkinsfile
--- a/devops/Jenkinsfile
+++ b/devops/Jenkinsfile
@@ -76,10 +76,19 @@ pipeline {
       steps{
         sh '''
         for i in {1..10}; do
-          curl -f http://localhost:8084/hello && break
+          echo "Intento $i de conexión al endpoint..."
+
+          if curl -f http://localhost:8084/hello; then
+            echo "Endpoint funcionando correctamente"
+            exit 0
+          fi
+
           echo "Esperando a que arranque la app..."
           sleep 5
         done
+
+        echo "ERROR: la aplicación no responde después de varios intentos"
+        exit 1
         '''
       }
     }
